# Generated by Django 5.1.dev20231109130319 on 2023-11-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='nonspecified', max_length=30, unique='true')),
                ('lastName', models.CharField(default='nonspecified', max_length=30)),
                ('date', models.DateField(auto_now_add=True)),
                ('address', models.CharField(default='nonspecified', max_length=100, unique='true')),
                ('code', models.CharField(default='nonspecified', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.UUIDField(primary_key='true', serialize=False)),
                ('product_code', models.CharField(default='nonspecified', max_length=20)),
                ('product_modified_at', models.TimeField(auto_now_add=True)),
                ('product_created_at', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
