# Generated by Django 5.1.dev20231109130319 on 2023-11-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_active',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='products',
            name='product_created_by',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='product_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='product_image',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='products',
            name='product_modified_by',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='product_name',
            field=models.CharField(default='nonspecified', max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='products',
            name='product_price',
            field=models.IntegerField(default=0),
        ),
    ]
