# Generated by Django 5.1.dev20231109130319 on 2023-11-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizar', '0002_products_product_active_products_product_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_modified_by',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_price',
            field=models.FloatField(default=0),
        ),
    ]
