# Generated by Django 5.1.dev20231109130319 on 2023-11-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizar', '0003_alter_products_product_modified_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_modified_at',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_modified_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
